apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{ .Values.services.srvxs.name }}
spec:
  gateway: {{ .Values.gateway }}
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - DELETE
  service:
    host: {{ .Values.services.srvxs.name }}.{{ .Values.clusterDomain }}
    name: {{ .Values.services.srvxs.name }}
    port: {{ .Values.services.srvxs.service.port }}