apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: {{ .Values.services.srv.name }}
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - DELETE
  service:
    host: {{ .Values.services.srv.name }}
    name: {{ .Values.services.srv.name }}
    port: {{ .Values.services.srv.service.port }}