dockerID: <%= dockerID %>
<% if(authentication){ -%>
clusterDomain: <%= clusterDomain %>
<% } -%>
services:
  app:
    name: <%= projectName %>
  srv:
    name: <%= projectName %>-srv
    image:
      repository: <%= projectName %>-srv
      tag: "latest"
      pullPolicy: Always
      imagePullSecretName: docker-config
      port: 5001
    service:
      port: 5001
<% if(authentication || apiS4HC || apiGraph || apiDest){ -%>
  uaa:
    name: <%= projectName %>-uaa
    bindingName: <%= projectName %>-uaa-binding
    bindingSecretName: <%= projectName %>-uaa-binding-secret
<% } -%>
<% if(apiS4HC || apiGraph || apiDest){ -%>
  dest:
    name: <%= projectName %>-dest
    bindingName: <%= projectName %>-dest-binding
    bindingSecretName: <%= projectName %>-dest-binding-secret
<% if(apiS4HC || apiGraph){ -%>
    ApplicationInterfaceKey: <SetValue>
<% if(apiS4HC){ -%>
    APIKey: <SetValue>
<% } -%>
<% if(apiGraph){ -%>
    graph:
      clientId: <SetValue>
      clientSecret: <SetValue>
<% if(!apiGraphSameSubaccount){ -%>
      alias: <SetValue>
<% } -%>
<% } -%>
<% } -%>
<% } -%>
<% if(hana){ -%>
  hdi:
    name: <%= projectName %>-hdi
    bindingName: <%= projectName %>-hdi-binding
    bindingSecretName: <%= projectName %>-hdi-binding-secret
<% } -%>